// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tradfri.proto

package grpc_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceMetadata struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor               string   `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceMetadata) Reset()         { *m = DeviceMetadata{} }
func (m *DeviceMetadata) String() string { return proto.CompactTextString(m) }
func (*DeviceMetadata) ProtoMessage()    {}
func (*DeviceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{0}
}

func (m *DeviceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceMetadata.Unmarshal(m, b)
}
func (m *DeviceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceMetadata.Marshal(b, m, deterministic)
}
func (m *DeviceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceMetadata.Merge(m, src)
}
func (m *DeviceMetadata) XXX_Size() int {
	return xxx_messageInfo_DeviceMetadata.Size(m)
}
func (m *DeviceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceMetadata proto.InternalMessageInfo

func (m *DeviceMetadata) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeviceMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceMetadata) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DeviceMetadata) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Device struct {
	Metadata             *DeviceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Dimmer               int32           `protobuf:"varint,2,opt,name=dimmer,proto3" json:"dimmer,omitempty"`
	Xcolor               int32           `protobuf:"varint,3,opt,name=xcolor,proto3" json:"xcolor,omitempty"`
	Ycolor               int32           `protobuf:"varint,4,opt,name=ycolor,proto3" json:"ycolor,omitempty"`
	Rgb                  string          `protobuf:"bytes,5,opt,name=rgb,proto3" json:"rgb,omitempty"`
	Power                bool            `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetMetadata() *DeviceMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Device) GetDimmer() int32 {
	if m != nil {
		return m.Dimmer
	}
	return 0
}

func (m *Device) GetXcolor() int32 {
	if m != nil {
		return m.Xcolor
	}
	return 0
}

func (m *Device) GetYcolor() int32 {
	if m != nil {
		return m.Ycolor
	}
	return 0
}

func (m *Device) GetRgb() string {
	if m != nil {
		return m.Rgb
	}
	return ""
}

func (m *Device) GetPower() bool {
	if m != nil {
		return m.Power
	}
	return false
}

type Group struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Power                int32    `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	Created              string   `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Devices              []int32  `protobuf:"varint,4,rep,packed,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{2}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *Group) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Group) GetDevices() []int32 {
	if m != nil {
		return m.Devices
	}
	return nil
}

type ListGroupsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{3}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

type ListGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{4}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetGroupRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{5}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{6}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListDevicesRequest struct {
	GroupId              int32    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesRequest) Reset()         { *m = ListDevicesRequest{} }
func (m *ListDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRequest) ProtoMessage()    {}
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{7}
}

func (m *ListDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRequest.Unmarshal(m, b)
}
func (m *ListDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRequest.Merge(m, src)
}
func (m *ListDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRequest.Size(m)
}
func (m *ListDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRequest proto.InternalMessageInfo

func (m *ListDevicesRequest) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type ListDevicesResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDevicesResponse) Reset()         { *m = ListDevicesResponse{} }
func (m *ListDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDevicesResponse) ProtoMessage()    {}
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{8}
}

func (m *ListDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesResponse.Unmarshal(m, b)
}
func (m *ListDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesResponse.Marshal(b, m, deterministic)
}
func (m *ListDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesResponse.Merge(m, src)
}
func (m *ListDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDevicesResponse.Size(m)
}
func (m *ListDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesResponse proto.InternalMessageInfo

func (m *ListDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type ListDeviceIDsRequest struct {
	GroupId              int32    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeviceIDsRequest) Reset()         { *m = ListDeviceIDsRequest{} }
func (m *ListDeviceIDsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeviceIDsRequest) ProtoMessage()    {}
func (*ListDeviceIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{9}
}

func (m *ListDeviceIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceIDsRequest.Unmarshal(m, b)
}
func (m *ListDeviceIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceIDsRequest.Marshal(b, m, deterministic)
}
func (m *ListDeviceIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceIDsRequest.Merge(m, src)
}
func (m *ListDeviceIDsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeviceIDsRequest.Size(m)
}
func (m *ListDeviceIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceIDsRequest proto.InternalMessageInfo

func (m *ListDeviceIDsRequest) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type ListDeviceIDsResponse struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeviceIDsResponse) Reset()         { *m = ListDeviceIDsResponse{} }
func (m *ListDeviceIDsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeviceIDsResponse) ProtoMessage()    {}
func (*ListDeviceIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{10}
}

func (m *ListDeviceIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeviceIDsResponse.Unmarshal(m, b)
}
func (m *ListDeviceIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeviceIDsResponse.Marshal(b, m, deterministic)
}
func (m *ListDeviceIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeviceIDsResponse.Merge(m, src)
}
func (m *ListDeviceIDsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeviceIDsResponse.Size(m)
}
func (m *ListDeviceIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeviceIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeviceIDsResponse proto.InternalMessageInfo

func (m *ListDeviceIDsResponse) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetDeviceRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceRequest) Reset()         { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()    {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{11}
}

func (m *GetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceRequest.Unmarshal(m, b)
}
func (m *GetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceRequest.Merge(m, src)
}
func (m *GetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceRequest.Size(m)
}
func (m *GetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceRequest proto.InternalMessageInfo

func (m *GetDeviceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDeviceResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceResponse) Reset()         { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()    {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{12}
}

func (m *GetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResponse.Unmarshal(m, b)
}
func (m *GetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResponse.Merge(m, src)
}
func (m *GetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResponse.Size(m)
}
func (m *GetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResponse proto.InternalMessageInfo

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type ChangeDeviceColorRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Xcolor               int32    `protobuf:"varint,2,opt,name=xcolor,proto3" json:"xcolor,omitempty"`
	Ycolor               int32    `protobuf:"varint,3,opt,name=ycolor,proto3" json:"ycolor,omitempty"`
	Rgb                  string   `protobuf:"bytes,4,opt,name=rgb,proto3" json:"rgb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDeviceColorRequest) Reset()         { *m = ChangeDeviceColorRequest{} }
func (m *ChangeDeviceColorRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeDeviceColorRequest) ProtoMessage()    {}
func (*ChangeDeviceColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{13}
}

func (m *ChangeDeviceColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDeviceColorRequest.Unmarshal(m, b)
}
func (m *ChangeDeviceColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDeviceColorRequest.Marshal(b, m, deterministic)
}
func (m *ChangeDeviceColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDeviceColorRequest.Merge(m, src)
}
func (m *ChangeDeviceColorRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeDeviceColorRequest.Size(m)
}
func (m *ChangeDeviceColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDeviceColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDeviceColorRequest proto.InternalMessageInfo

func (m *ChangeDeviceColorRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChangeDeviceColorRequest) GetXcolor() int32 {
	if m != nil {
		return m.Xcolor
	}
	return 0
}

func (m *ChangeDeviceColorRequest) GetYcolor() int32 {
	if m != nil {
		return m.Ycolor
	}
	return 0
}

func (m *ChangeDeviceColorRequest) GetRgb() string {
	if m != nil {
		return m.Rgb
	}
	return ""
}

type ChangeDeviceColorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDeviceColorResponse) Reset()         { *m = ChangeDeviceColorResponse{} }
func (m *ChangeDeviceColorResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeDeviceColorResponse) ProtoMessage()    {}
func (*ChangeDeviceColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{14}
}

func (m *ChangeDeviceColorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDeviceColorResponse.Unmarshal(m, b)
}
func (m *ChangeDeviceColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDeviceColorResponse.Marshal(b, m, deterministic)
}
func (m *ChangeDeviceColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDeviceColorResponse.Merge(m, src)
}
func (m *ChangeDeviceColorResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeDeviceColorResponse.Size(m)
}
func (m *ChangeDeviceColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDeviceColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDeviceColorResponse proto.InternalMessageInfo

type ChangeDeviceDimmingRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDeviceDimmingRequest) Reset()         { *m = ChangeDeviceDimmingRequest{} }
func (m *ChangeDeviceDimmingRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeDeviceDimmingRequest) ProtoMessage()    {}
func (*ChangeDeviceDimmingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{15}
}

func (m *ChangeDeviceDimmingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDeviceDimmingRequest.Unmarshal(m, b)
}
func (m *ChangeDeviceDimmingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDeviceDimmingRequest.Marshal(b, m, deterministic)
}
func (m *ChangeDeviceDimmingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDeviceDimmingRequest.Merge(m, src)
}
func (m *ChangeDeviceDimmingRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeDeviceDimmingRequest.Size(m)
}
func (m *ChangeDeviceDimmingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDeviceDimmingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDeviceDimmingRequest proto.InternalMessageInfo

func (m *ChangeDeviceDimmingRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChangeDeviceDimmingRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ChangeDeviceDimmingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDeviceDimmingResponse) Reset()         { *m = ChangeDeviceDimmingResponse{} }
func (m *ChangeDeviceDimmingResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeDeviceDimmingResponse) ProtoMessage()    {}
func (*ChangeDeviceDimmingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{16}
}

func (m *ChangeDeviceDimmingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDeviceDimmingResponse.Unmarshal(m, b)
}
func (m *ChangeDeviceDimmingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDeviceDimmingResponse.Marshal(b, m, deterministic)
}
func (m *ChangeDeviceDimmingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDeviceDimmingResponse.Merge(m, src)
}
func (m *ChangeDeviceDimmingResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeDeviceDimmingResponse.Size(m)
}
func (m *ChangeDeviceDimmingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDeviceDimmingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDeviceDimmingResponse proto.InternalMessageInfo

type TurnDeviceOnRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnDeviceOnRequest) Reset()         { *m = TurnDeviceOnRequest{} }
func (m *TurnDeviceOnRequest) String() string { return proto.CompactTextString(m) }
func (*TurnDeviceOnRequest) ProtoMessage()    {}
func (*TurnDeviceOnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{17}
}

func (m *TurnDeviceOnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnDeviceOnRequest.Unmarshal(m, b)
}
func (m *TurnDeviceOnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnDeviceOnRequest.Marshal(b, m, deterministic)
}
func (m *TurnDeviceOnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnDeviceOnRequest.Merge(m, src)
}
func (m *TurnDeviceOnRequest) XXX_Size() int {
	return xxx_messageInfo_TurnDeviceOnRequest.Size(m)
}
func (m *TurnDeviceOnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnDeviceOnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TurnDeviceOnRequest proto.InternalMessageInfo

func (m *TurnDeviceOnRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TurnDeviceOnResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnDeviceOnResponse) Reset()         { *m = TurnDeviceOnResponse{} }
func (m *TurnDeviceOnResponse) String() string { return proto.CompactTextString(m) }
func (*TurnDeviceOnResponse) ProtoMessage()    {}
func (*TurnDeviceOnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{18}
}

func (m *TurnDeviceOnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnDeviceOnResponse.Unmarshal(m, b)
}
func (m *TurnDeviceOnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnDeviceOnResponse.Marshal(b, m, deterministic)
}
func (m *TurnDeviceOnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnDeviceOnResponse.Merge(m, src)
}
func (m *TurnDeviceOnResponse) XXX_Size() int {
	return xxx_messageInfo_TurnDeviceOnResponse.Size(m)
}
func (m *TurnDeviceOnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnDeviceOnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TurnDeviceOnResponse proto.InternalMessageInfo

type TurnDeviceOffRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnDeviceOffRequest) Reset()         { *m = TurnDeviceOffRequest{} }
func (m *TurnDeviceOffRequest) String() string { return proto.CompactTextString(m) }
func (*TurnDeviceOffRequest) ProtoMessage()    {}
func (*TurnDeviceOffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{19}
}

func (m *TurnDeviceOffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnDeviceOffRequest.Unmarshal(m, b)
}
func (m *TurnDeviceOffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnDeviceOffRequest.Marshal(b, m, deterministic)
}
func (m *TurnDeviceOffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnDeviceOffRequest.Merge(m, src)
}
func (m *TurnDeviceOffRequest) XXX_Size() int {
	return xxx_messageInfo_TurnDeviceOffRequest.Size(m)
}
func (m *TurnDeviceOffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnDeviceOffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TurnDeviceOffRequest proto.InternalMessageInfo

func (m *TurnDeviceOffRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TurnDeviceOffResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TurnDeviceOffResponse) Reset()         { *m = TurnDeviceOffResponse{} }
func (m *TurnDeviceOffResponse) String() string { return proto.CompactTextString(m) }
func (*TurnDeviceOffResponse) ProtoMessage()    {}
func (*TurnDeviceOffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f669820b67678c6, []int{20}
}

func (m *TurnDeviceOffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TurnDeviceOffResponse.Unmarshal(m, b)
}
func (m *TurnDeviceOffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TurnDeviceOffResponse.Marshal(b, m, deterministic)
}
func (m *TurnDeviceOffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TurnDeviceOffResponse.Merge(m, src)
}
func (m *TurnDeviceOffResponse) XXX_Size() int {
	return xxx_messageInfo_TurnDeviceOffResponse.Size(m)
}
func (m *TurnDeviceOffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TurnDeviceOffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TurnDeviceOffResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeviceMetadata)(nil), "grpc_server.DeviceMetadata")
	proto.RegisterType((*Device)(nil), "grpc_server.Device")
	proto.RegisterType((*Group)(nil), "grpc_server.Group")
	proto.RegisterType((*ListGroupsRequest)(nil), "grpc_server.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "grpc_server.ListGroupsResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "grpc_server.GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "grpc_server.GetGroupResponse")
	proto.RegisterType((*ListDevicesRequest)(nil), "grpc_server.ListDevicesRequest")
	proto.RegisterType((*ListDevicesResponse)(nil), "grpc_server.ListDevicesResponse")
	proto.RegisterType((*ListDeviceIDsRequest)(nil), "grpc_server.ListDeviceIDsRequest")
	proto.RegisterType((*ListDeviceIDsResponse)(nil), "grpc_server.ListDeviceIDsResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "grpc_server.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "grpc_server.GetDeviceResponse")
	proto.RegisterType((*ChangeDeviceColorRequest)(nil), "grpc_server.ChangeDeviceColorRequest")
	proto.RegisterType((*ChangeDeviceColorResponse)(nil), "grpc_server.ChangeDeviceColorResponse")
	proto.RegisterType((*ChangeDeviceDimmingRequest)(nil), "grpc_server.ChangeDeviceDimmingRequest")
	proto.RegisterType((*ChangeDeviceDimmingResponse)(nil), "grpc_server.ChangeDeviceDimmingResponse")
	proto.RegisterType((*TurnDeviceOnRequest)(nil), "grpc_server.TurnDeviceOnRequest")
	proto.RegisterType((*TurnDeviceOnResponse)(nil), "grpc_server.TurnDeviceOnResponse")
	proto.RegisterType((*TurnDeviceOffRequest)(nil), "grpc_server.TurnDeviceOffRequest")
	proto.RegisterType((*TurnDeviceOffResponse)(nil), "grpc_server.TurnDeviceOffResponse")
}

func init() { proto.RegisterFile("tradfri.proto", fileDescriptor_7f669820b67678c6) }

var fileDescriptor_7f669820b67678c6 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdf, 0x4f, 0xd4, 0x40,
	0x10, 0xe6, 0x7e, 0xb4, 0x1c, 0x73, 0x82, 0xb0, 0x77, 0x60, 0x29, 0x82, 0x65, 0x13, 0xb0, 0x6a,
	0xc4, 0x88, 0x0f, 0xbe, 0xf8, 0x40, 0xe4, 0x12, 0x42, 0x82, 0x21, 0xa9, 0x98, 0xf8, 0x86, 0xe5,
	0xba, 0x9c, 0x35, 0xd7, 0x1f, 0x6e, 0x7b, 0xa7, 0xfc, 0x4d, 0x3e, 0xf9, 0x1f, 0x9a, 0xee, 0xee,
	0x6d, 0xbb, 0x77, 0x5d, 0xf0, 0x6d, 0x67, 0xe6, 0x9b, 0xf9, 0x66, 0x67, 0xe7, 0x6b, 0x0a, 0xab,
	0x39, 0xf5, 0x83, 0x5b, 0x1a, 0x1e, 0xa5, 0x34, 0xc9, 0x13, 0xd4, 0x1d, 0xd1, 0x74, 0x78, 0x9d,
	0x11, 0x3a, 0x25, 0x14, 0x7f, 0x83, 0xb5, 0x01, 0x99, 0x86, 0x43, 0xf2, 0x89, 0xe4, 0x7e, 0xe0,
	0xe7, 0x3e, 0x5a, 0x83, 0x66, 0x18, 0x58, 0x0d, 0xa7, 0xe1, 0x1a, 0x5e, 0x33, 0x0c, 0x10, 0x82,
	0x76, 0xec, 0x47, 0xc4, 0x6a, 0x3a, 0x0d, 0x77, 0xc5, 0x63, 0x67, 0xb4, 0x05, 0xe6, 0x94, 0xc4,
	0x41, 0x42, 0xad, 0x16, 0xf3, 0x0a, 0xab, 0xc0, 0xe6, 0x77, 0x29, 0xb1, 0xda, 0x1c, 0x5b, 0x9c,
	0xf1, 0xdf, 0x06, 0x98, 0x9c, 0x02, 0xbd, 0x87, 0x4e, 0x24, 0x68, 0x18, 0x41, 0xf7, 0x78, 0xe7,
	0xa8, 0xd2, 0xcc, 0x91, 0xda, 0x89, 0x27, 0xc1, 0x05, 0x5f, 0x10, 0x46, 0x11, 0xa1, 0xac, 0x0b,
	0xc3, 0x13, 0x56, 0xe1, 0xff, 0x3d, 0x4c, 0xc6, 0xa2, 0x0f, 0xc3, 0x13, 0x56, 0xe1, 0xbf, 0xe3,
	0xfe, 0x36, 0xf7, 0x73, 0x0b, 0xad, 0x43, 0x8b, 0x8e, 0x6e, 0x2c, 0x83, 0xb5, 0x57, 0x1c, 0x51,
	0x1f, 0x8c, 0x34, 0xf9, 0x45, 0xa8, 0x65, 0x3a, 0x0d, 0xb7, 0xe3, 0x71, 0x03, 0xfb, 0x60, 0x9c,
	0xd1, 0x64, 0x92, 0x2e, 0x0c, 0x43, 0xc2, 0x79, 0x1f, 0xdc, 0x40, 0x16, 0x2c, 0x0f, 0x29, 0xf1,
	0x73, 0x12, 0x88, 0x79, 0xcc, 0xcc, 0x22, 0x12, 0xb0, 0x4b, 0x65, 0x56, 0xdb, 0x69, 0xb9, 0x86,
	0x37, 0x33, 0x71, 0x0f, 0x36, 0x2e, 0xc2, 0x2c, 0x67, 0x34, 0x99, 0x47, 0x7e, 0x4e, 0x48, 0x96,
	0xe3, 0x13, 0x40, 0x55, 0x67, 0x96, 0x26, 0x71, 0x46, 0xd0, 0x4b, 0x30, 0x47, 0xcc, 0x63, 0x35,
	0x9c, 0x96, 0xdb, 0x3d, 0x46, 0xca, 0xd0, 0x18, 0xd8, 0x13, 0x08, 0xbc, 0x0f, 0x8f, 0xcf, 0x08,
	0x2f, 0x20, 0x8a, 0xce, 0xdf, 0x01, 0x7f, 0x80, 0xf5, 0x12, 0x22, 0x28, 0x5c, 0x30, 0x58, 0x01,
	0xf1, 0x2c, 0x75, 0x0c, 0x1c, 0x80, 0xdf, 0xf0, 0x16, 0xf9, 0x53, 0xcd, 0x1a, 0x47, 0xdb, 0xd0,
	0x61, 0xe1, 0x6b, 0xc9, 0xb4, 0xcc, 0xec, 0xf3, 0x00, 0x0f, 0xa0, 0xa7, 0x24, 0x08, 0xc6, 0xd7,
	0xe5, 0x64, 0xf8, 0xad, 0x7a, 0x35, 0xab, 0x50, 0x8e, 0xeb, 0x2d, 0xf4, 0xcb, 0x2a, 0xe7, 0x83,
	0xff, 0x21, 0x7e, 0x01, 0x9b, 0x73, 0x29, 0x82, 0x7a, 0x1d, 0x5a, 0x61, 0xc0, 0x69, 0x0d, 0xaf,
	0x38, 0x62, 0xcc, 0x46, 0x22, 0x38, 0x35, 0x63, 0x3b, 0x81, 0x8d, 0x0a, 0x46, 0x94, 0x7a, 0x05,
	0x26, 0xef, 0x50, 0x0c, 0xae, 0xf6, 0x12, 0x02, 0x82, 0xc7, 0x60, 0x9d, 0x7e, 0xf7, 0xe3, 0x11,
	0xe1, 0xfe, 0xd3, 0x62, 0x25, 0x35, 0x6c, 0x95, 0xcd, 0x6e, 0x6a, 0x36, 0xbb, 0x55, 0xb7, 0xd9,
	0x6d, 0xb9, 0xd9, 0x78, 0x07, 0xb6, 0x6b, 0xd8, 0x78, 0xdf, 0xf8, 0x23, 0xd8, 0xd5, 0xe0, 0x20,
	0x8c, 0xa2, 0x30, 0x1e, 0xe9, 0x9a, 0xe9, 0x83, 0x31, 0xf5, 0xc7, 0x13, 0x32, 0xdb, 0x7a, 0x66,
	0xe0, 0x5d, 0xd8, 0xa9, 0xad, 0x21, 0x28, 0x0e, 0xa0, 0x77, 0x35, 0xa1, 0x31, 0x0f, 0x5e, 0xc6,
	0xba, 0xb1, 0x6e, 0x41, 0x5f, 0x85, 0x89, 0xf4, 0x43, 0xc5, 0x7f, 0x7b, 0xab, 0xcb, 0x7f, 0x02,
	0x9b, 0x73, 0x38, 0x5e, 0xe0, 0xf8, 0x8f, 0x09, 0x6b, 0x57, 0xfc, 0xc3, 0xf7, 0x99, 0x50, 0xf6,
	0xfd, 0xb9, 0x04, 0x28, 0xe5, 0x85, 0xf6, 0x94, 0xb7, 0x5a, 0x10, 0xa3, 0xfd, 0x4c, 0x1b, 0x17,
	0x2d, 0x2e, 0xa1, 0x73, 0xe8, 0xcc, 0xa4, 0x84, 0x9e, 0xaa, 0x9a, 0x51, 0x45, 0x68, 0xef, 0x6a,
	0xa2, 0xb2, 0x94, 0x07, 0xdd, 0x8a, 0x4c, 0xd0, 0x22, 0xb9, 0xaa, 0x38, 0xdb, 0xd1, 0x03, 0x64,
	0xcd, 0xaf, 0xb0, 0xaa, 0x28, 0x00, 0xed, 0x6b, 0x92, 0x4a, 0x41, 0xd9, 0xf8, 0x3e, 0x88, 0xac,
	0x7c, 0x01, 0x2b, 0x52, 0x0c, 0x68, 0xe1, 0x6e, 0x8a, 0x90, 0xec, 0x3d, 0x5d, 0x58, 0x56, 0x0b,
	0x60, 0x63, 0x61, 0x55, 0xd1, 0x81, 0x92, 0xa6, 0x13, 0x8e, 0x7d, 0xf8, 0x10, 0x4c, 0xb2, 0xfc,
	0x80, 0x5e, 0xcd, 0xbe, 0xa2, 0xe7, 0xda, 0x02, 0xaa, 0x2a, 0x6c, 0xf7, 0x61, 0xa0, 0xe4, 0xfa,
	0x02, 0x8f, 0xaa, 0x5b, 0x8d, 0xd4, 0xd7, 0xaa, 0xd1, 0x85, 0xbd, 0x7f, 0x0f, 0xa2, 0xfa, 0xa0,
	0xca, 0xb2, 0x23, 0x6d, 0x96, 0x14, 0xcc, 0xdc, 0x83, 0xd6, 0x6a, 0x05, 0x2f, 0xdd, 0x98, 0xec,
	0xdf, 0xe0, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xed, 0xd7, 0x68, 0x2c, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradfriServiceClient is the client API for TradfriService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradfriServiceClient interface {
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ListDeviceIDs(ctx context.Context, in *ListDeviceIDsRequest, opts ...grpc.CallOption) (*ListDeviceIDsResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	ChangeDeviceColor(ctx context.Context, in *ChangeDeviceColorRequest, opts ...grpc.CallOption) (*ChangeDeviceColorResponse, error)
	ChangeDeviceDimming(ctx context.Context, in *ChangeDeviceDimmingRequest, opts ...grpc.CallOption) (*ChangeDeviceDimmingResponse, error)
	TurnDeviceOn(ctx context.Context, in *TurnDeviceOnRequest, opts ...grpc.CallOption) (*TurnDeviceOnResponse, error)
	TurnDeviceOff(ctx context.Context, in *TurnDeviceOffRequest, opts ...grpc.CallOption) (*TurnDeviceOffResponse, error)
}

type tradfriServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradfriServiceClient(cc *grpc.ClientConn) TradfriServiceClient {
	return &tradfriServiceClient{cc}
}

func (c *tradfriServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ListDeviceIDs(ctx context.Context, in *ListDeviceIDsRequest, opts ...grpc.CallOption) (*ListDeviceIDsResponse, error) {
	out := new(ListDeviceIDsResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/ListDeviceIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ChangeDeviceColor(ctx context.Context, in *ChangeDeviceColorRequest, opts ...grpc.CallOption) (*ChangeDeviceColorResponse, error) {
	out := new(ChangeDeviceColorResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/ChangeDeviceColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ChangeDeviceDimming(ctx context.Context, in *ChangeDeviceDimmingRequest, opts ...grpc.CallOption) (*ChangeDeviceDimmingResponse, error) {
	out := new(ChangeDeviceDimmingResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/ChangeDeviceDimming", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) TurnDeviceOn(ctx context.Context, in *TurnDeviceOnRequest, opts ...grpc.CallOption) (*TurnDeviceOnResponse, error) {
	out := new(TurnDeviceOnResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/TurnDeviceOn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) TurnDeviceOff(ctx context.Context, in *TurnDeviceOffRequest, opts ...grpc.CallOption) (*TurnDeviceOffResponse, error) {
	out := new(TurnDeviceOffResponse)
	err := c.cc.Invoke(ctx, "/grpc_server.TradfriService/TurnDeviceOff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradfriServiceServer is the server API for TradfriService service.
type TradfriServiceServer interface {
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListDeviceIDs(context.Context, *ListDeviceIDsRequest) (*ListDeviceIDsResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	ChangeDeviceColor(context.Context, *ChangeDeviceColorRequest) (*ChangeDeviceColorResponse, error)
	ChangeDeviceDimming(context.Context, *ChangeDeviceDimmingRequest) (*ChangeDeviceDimmingResponse, error)
	TurnDeviceOn(context.Context, *TurnDeviceOnRequest) (*TurnDeviceOnResponse, error)
	TurnDeviceOff(context.Context, *TurnDeviceOffRequest) (*TurnDeviceOffResponse, error)
}

func RegisterTradfriServiceServer(s *grpc.Server, srv TradfriServiceServer) {
	s.RegisterService(&_TradfriService_serviceDesc, srv)
}

func _TradfriService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ListDeviceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListDeviceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/ListDeviceIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListDeviceIDs(ctx, req.(*ListDeviceIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ChangeDeviceColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDeviceColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ChangeDeviceColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/ChangeDeviceColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ChangeDeviceColor(ctx, req.(*ChangeDeviceColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ChangeDeviceDimming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDeviceDimmingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ChangeDeviceDimming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/ChangeDeviceDimming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ChangeDeviceDimming(ctx, req.(*ChangeDeviceDimmingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_TurnDeviceOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnDeviceOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).TurnDeviceOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/TurnDeviceOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).TurnDeviceOn(ctx, req.(*TurnDeviceOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_TurnDeviceOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnDeviceOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).TurnDeviceOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_server.TradfriService/TurnDeviceOff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).TurnDeviceOff(ctx, req.(*TurnDeviceOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradfriService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_server.TradfriService",
	HandlerType: (*TradfriServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _TradfriService_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _TradfriService_GetGroup_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _TradfriService_ListDevices_Handler,
		},
		{
			MethodName: "ListDeviceIDs",
			Handler:    _TradfriService_ListDeviceIDs_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _TradfriService_GetDevice_Handler,
		},
		{
			MethodName: "ChangeDeviceColor",
			Handler:    _TradfriService_ChangeDeviceColor_Handler,
		},
		{
			MethodName: "ChangeDeviceDimming",
			Handler:    _TradfriService_ChangeDeviceDimming_Handler,
		},
		{
			MethodName: "TurnDeviceOn",
			Handler:    _TradfriService_TurnDeviceOn_Handler,
		},
		{
			MethodName: "TurnDeviceOff",
			Handler:    _TradfriService_TurnDeviceOff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradfri.proto",
}
