// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: tradfri.proto

package golang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradfriService_ListGroups_FullMethodName              = "/grpc_server.TradfriService/ListGroups"
	TradfriService_GetGroup_FullMethodName                = "/grpc_server.TradfriService/GetGroup"
	TradfriService_ListDevices_FullMethodName             = "/grpc_server.TradfriService/ListDevices"
	TradfriService_ListDeviceIDs_FullMethodName           = "/grpc_server.TradfriService/ListDeviceIDs"
	TradfriService_GetDevice_FullMethodName               = "/grpc_server.TradfriService/GetDevice"
	TradfriService_ChangeDeviceColor_FullMethodName       = "/grpc_server.TradfriService/ChangeDeviceColor"
	TradfriService_ChangeDeviceDimming_FullMethodName     = "/grpc_server.TradfriService/ChangeDeviceDimming"
	TradfriService_TurnDeviceOn_FullMethodName            = "/grpc_server.TradfriService/TurnDeviceOn"
	TradfriService_TurnDeviceOff_FullMethodName           = "/grpc_server.TradfriService/TurnDeviceOff"
	TradfriService_ChangeDevicePositioning_FullMethodName = "/grpc_server.TradfriService/ChangeDevicePositioning"
)

// TradfriServiceClient is the client API for TradfriService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The tradfri service definition
type TradfriServiceClient interface {
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ListDeviceIDs(ctx context.Context, in *ListDeviceIDsRequest, opts ...grpc.CallOption) (*ListDeviceIDsResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	ChangeDeviceColor(ctx context.Context, in *ChangeDeviceColorRequest, opts ...grpc.CallOption) (*ChangeDeviceColorResponse, error)
	ChangeDeviceDimming(ctx context.Context, in *ChangeDeviceDimmingRequest, opts ...grpc.CallOption) (*ChangeDeviceDimmingResponse, error)
	TurnDeviceOn(ctx context.Context, in *TurnDeviceOnRequest, opts ...grpc.CallOption) (*TurnDeviceOnResponse, error)
	TurnDeviceOff(ctx context.Context, in *TurnDeviceOffRequest, opts ...grpc.CallOption) (*TurnDeviceOffResponse, error)
	ChangeDevicePositioning(ctx context.Context, in *ChangeDevicePositioningRequest, opts ...grpc.CallOption) (*ChangeDevicePositioningResponse, error)
}

type tradfriServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradfriServiceClient(cc grpc.ClientConnInterface) TradfriServiceClient {
	return &tradfriServiceClient{cc}
}

func (c *tradfriServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, TradfriService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, TradfriService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, TradfriService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ListDeviceIDs(ctx context.Context, in *ListDeviceIDsRequest, opts ...grpc.CallOption) (*ListDeviceIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeviceIDsResponse)
	err := c.cc.Invoke(ctx, TradfriService_ListDeviceIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, TradfriService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ChangeDeviceColor(ctx context.Context, in *ChangeDeviceColorRequest, opts ...grpc.CallOption) (*ChangeDeviceColorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeDeviceColorResponse)
	err := c.cc.Invoke(ctx, TradfriService_ChangeDeviceColor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ChangeDeviceDimming(ctx context.Context, in *ChangeDeviceDimmingRequest, opts ...grpc.CallOption) (*ChangeDeviceDimmingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeDeviceDimmingResponse)
	err := c.cc.Invoke(ctx, TradfriService_ChangeDeviceDimming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) TurnDeviceOn(ctx context.Context, in *TurnDeviceOnRequest, opts ...grpc.CallOption) (*TurnDeviceOnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurnDeviceOnResponse)
	err := c.cc.Invoke(ctx, TradfriService_TurnDeviceOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) TurnDeviceOff(ctx context.Context, in *TurnDeviceOffRequest, opts ...grpc.CallOption) (*TurnDeviceOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurnDeviceOffResponse)
	err := c.cc.Invoke(ctx, TradfriService_TurnDeviceOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradfriServiceClient) ChangeDevicePositioning(ctx context.Context, in *ChangeDevicePositioningRequest, opts ...grpc.CallOption) (*ChangeDevicePositioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeDevicePositioningResponse)
	err := c.cc.Invoke(ctx, TradfriService_ChangeDevicePositioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradfriServiceServer is the server API for TradfriService service.
// All implementations should embed UnimplementedTradfriServiceServer
// for forward compatibility.
//
// The tradfri service definition
type TradfriServiceServer interface {
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListDeviceIDs(context.Context, *ListDeviceIDsRequest) (*ListDeviceIDsResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	ChangeDeviceColor(context.Context, *ChangeDeviceColorRequest) (*ChangeDeviceColorResponse, error)
	ChangeDeviceDimming(context.Context, *ChangeDeviceDimmingRequest) (*ChangeDeviceDimmingResponse, error)
	TurnDeviceOn(context.Context, *TurnDeviceOnRequest) (*TurnDeviceOnResponse, error)
	TurnDeviceOff(context.Context, *TurnDeviceOffRequest) (*TurnDeviceOffResponse, error)
	ChangeDevicePositioning(context.Context, *ChangeDevicePositioningRequest) (*ChangeDevicePositioningResponse, error)
}

// UnimplementedTradfriServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradfriServiceServer struct{}

func (UnimplementedTradfriServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedTradfriServiceServer) GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedTradfriServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedTradfriServiceServer) ListDeviceIDs(context.Context, *ListDeviceIDsRequest) (*ListDeviceIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeviceIDs not implemented")
}
func (UnimplementedTradfriServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedTradfriServiceServer) ChangeDeviceColor(context.Context, *ChangeDeviceColorRequest) (*ChangeDeviceColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDeviceColor not implemented")
}
func (UnimplementedTradfriServiceServer) ChangeDeviceDimming(context.Context, *ChangeDeviceDimmingRequest) (*ChangeDeviceDimmingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDeviceDimming not implemented")
}
func (UnimplementedTradfriServiceServer) TurnDeviceOn(context.Context, *TurnDeviceOnRequest) (*TurnDeviceOnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurnDeviceOn not implemented")
}
func (UnimplementedTradfriServiceServer) TurnDeviceOff(context.Context, *TurnDeviceOffRequest) (*TurnDeviceOffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurnDeviceOff not implemented")
}
func (UnimplementedTradfriServiceServer) ChangeDevicePositioning(context.Context, *ChangeDevicePositioningRequest) (*ChangeDevicePositioningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDevicePositioning not implemented")
}
func (UnimplementedTradfriServiceServer) testEmbeddedByValue() {}

// UnsafeTradfriServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradfriServiceServer will
// result in compilation errors.
type UnsafeTradfriServiceServer interface {
	mustEmbedUnimplementedTradfriServiceServer()
}

func RegisterTradfriServiceServer(s grpc.ServiceRegistrar, srv TradfriServiceServer) {
	// If the following call pancis, it indicates UnimplementedTradfriServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradfriService_ServiceDesc, srv)
}

func _TradfriService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ListDeviceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ListDeviceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ListDeviceIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ListDeviceIDs(ctx, req.(*ListDeviceIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ChangeDeviceColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDeviceColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ChangeDeviceColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ChangeDeviceColor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ChangeDeviceColor(ctx, req.(*ChangeDeviceColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ChangeDeviceDimming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDeviceDimmingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ChangeDeviceDimming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ChangeDeviceDimming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ChangeDeviceDimming(ctx, req.(*ChangeDeviceDimmingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_TurnDeviceOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnDeviceOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).TurnDeviceOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_TurnDeviceOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).TurnDeviceOn(ctx, req.(*TurnDeviceOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_TurnDeviceOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurnDeviceOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).TurnDeviceOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_TurnDeviceOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).TurnDeviceOff(ctx, req.(*TurnDeviceOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradfriService_ChangeDevicePositioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDevicePositioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradfriServiceServer).ChangeDevicePositioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradfriService_ChangeDevicePositioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradfriServiceServer).ChangeDevicePositioning(ctx, req.(*ChangeDevicePositioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradfriService_ServiceDesc is the grpc.ServiceDesc for TradfriService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradfriService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_server.TradfriService",
	HandlerType: (*TradfriServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _TradfriService_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _TradfriService_GetGroup_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _TradfriService_ListDevices_Handler,
		},
		{
			MethodName: "ListDeviceIDs",
			Handler:    _TradfriService_ListDeviceIDs_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _TradfriService_GetDevice_Handler,
		},
		{
			MethodName: "ChangeDeviceColor",
			Handler:    _TradfriService_ChangeDeviceColor_Handler,
		},
		{
			MethodName: "ChangeDeviceDimming",
			Handler:    _TradfriService_ChangeDeviceDimming_Handler,
		},
		{
			MethodName: "TurnDeviceOn",
			Handler:    _TradfriService_TurnDeviceOn_Handler,
		},
		{
			MethodName: "TurnDeviceOff",
			Handler:    _TradfriService_TurnDeviceOff_Handler,
		},
		{
			MethodName: "ChangeDevicePositioning",
			Handler:    _TradfriService_ChangeDevicePositioning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradfri.proto",
}
